name: 'Terraform'
` 
on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init 

    - name: Terraform Format
      run: terraform fmt 
      
    - name: Terraform Plan
      run: terraform plan -input=false 

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false
