# buildspec.yml for Notification API
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=339713022791.dkr.ecr.us-east-1.amazonaws.com/notification-api
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t notification-api .
      - docker tag notification-api:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
